const { REST, Routes, ApplicationCommandOptionType } = require("discord.js");
require("dotenv").config();

const commands = [
  {
    name: "ping",
    description: "Replies with pong!"
  },
  {
    name: "add",
    description: "Adds two numbers",
    options: [
      {
        name: "first-number",
        description: "The first number being added",
        type: ApplicationCommandOptionType.Number,
        required: true,
      },
      {
        name: "second-number",
        description: "The second number being added",
        type: ApplicationCommandOptionType.Number,
        required: true,
      }
    ]
  },
  {
    name: "prompt",
    description: "Replies with text generated by chatGPT based on your prompt",
    options: [
      {
        name: "prompt",
        description: "your prompt",
        type: ApplicationCommandOptionType.String,
        required: true
      }
    ]
  },
];

const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_BOT_TOKEN);

(async () => {
  try {
    await rest.put(
      Routes.applicationGuildCommands(process.env.BOT_ID, process.env.SERVER_ID),
      { body: commands }
    );
    console.log(`Registered commands successfully`);
  } catch (err) {
    console.log("Error: ", err);
  }
})();
