const { REST, Routes } = require("discord.js");
require("dotenv").config();

const commands = [
  {
    name: "ping",
    description: "Replies with pong!"
  },
  {
    name: "prompt",
    description: "Replies with text generated by chatGPT based on your prompt",
  },
];

const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_BOT_TOKEN);

(async () => {
  try {
    await rest.put(
      Routes.applicationGuildCommands(process.env.BOT_ID, process.env.SERVER_ID),
      { body: commands }
    );
    console.log(`Registered commands ${commands[0].name} and ${commands[1].name} successfully`);
  } catch (err) {
    console.log("Error: ", err);
  }
})();
